[package]
name = "mcp-core"
license.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
description = "Core types for Model Context Protocol"


[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
schemars = "0.8"
anyhow = "1.0"
chrono = { version = "0.4.38", features = ["serde"] }
url = "2.5"
base64 = "0.21"

[dev-dependencies]
tempfile = "3.8"
